
eureka:
  instance:
    prefer-ip-address: true
  client:
    region: claimsChannel
    availability-zones:
      zones: Zones
    service-url:
       defaultZone : http://localhost:7070/eureka
#      claimsChannelZones : http://localhost:7070/eureka
       
  
zuul: 
  strip-prefix: false
  routes:
    api-a:
      path: /api-a/**
      serviceId: claims-channel-server
#    api-b:
#      path: /api-b/**
#      serviceId: netflix-ribbon
#    api-c:
#      path: /api-c/**
#      url: http://www.jd.com
