server:
  port: 7070
  session:
    timeout: 100
  tomcat:
    uri-encoding: UTF-8
spring:
  output:
    ansi:
      enabled: detect
 
eureka:
  server:
    enable-self-preservation: false  # 关闭自我保护
  instance:
    hostname: localhost
  client:
    region: claimsChannel
    availability-zones:
      zones: Zones
    register-with-eureka: false   # 关闭eureka客户端登记
    fetch-registry: false         # 关闭检查服务
    service-url:
#      claimsChannelZones : http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
       
      
      